version: "3.9"
services:
  backend:
    image: cccaaannn/simple-blog-backend:latest
    # build: .
    ports:
      - "3000:3000"    
    restart: unless-stopped
    networks:
      - custom_net
    deploy:
        resources:
            limits:
              memory: 512M
    volumes:
      - './logs:/app/logs'
    environment:
      # Db settings
      MONGO_CONNECTION_STRING: 'mongodb://<username>:<password>@localhost:27017/SimpleBlogDb?authSource=admin&readPreference=primary&appname=MongoDB&ssl=false'

      # JWT settings
      JWT_PRIVATE_KEY: ""
      JWT_USER_TOKEN_EXPIRATION: "2592000s"

      # Email settings
      EMAIL_SERVICE: "gmail"
      EMAIL_USERNAME: ""
      EMAIL_PASSWORD: ""

      # Recaptcha settings
      RECAPTCHA_SECRET_KEY: ""

      # Frontend settings
      FRONTEND_URL: "https://simple-blog-cccaaannn.vercel.app/"

networks:
  custom_net:
    name: custom_bridge_network
