name: Node CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node test
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: make test coverage
        run: |
          npm install
          npm run test:coverage-report
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
