name: Node CI

on:
  push:
    branches: [master]

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install and make test coverage
        run: |
          npm install
          npm run test:coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t cccaaannn/simple-blog-backend:latest .

      - name: Push Docker image
        run: docker push cccaaannn/simple-blog-backend

  heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push Docker to Heroku
        env:
          HEROKU_APP_NAME: simple-blog-backend-1
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          DOCKERFILE_NAME: "Dockerfile"
        run: |
          echo ${HEROKU_API_KEY} | docker login --username=${HEROKU_EMAIL} registry.heroku.com --password-stdin
          docker build --file ${DOCKERFILE_NAME} --tag registry.heroku.com/${HEROKU_APP_NAME}/web .
          heroku container:push --recursive --app ${HEROKU_APP_NAME}
          heroku container:release web --app ${HEROKU_APP_NAME}
